name: Lint/Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    with:
      SKIP_TEST: true
    uses: bitoroprotocol/actions-public/.github/workflows/v3-lint-build-test.yml@main
